from enum import Enum


class TrianguloEnum(Enum):
    NAO_FORMA_TRIANGULO = "NAO_FORMA_TRIANGULO"
    TRIANGULO_ISOSCELES = "TRIANGULO ISOSCELES"
    TRIANGULO_RETANGULO = "TRIANGULO RETANGULO"
    TRIANGULO_ACUTANGULO = "TRIANGULO ACUTANGULO"
    TRIANGULO_EQUILATERO = "TRIANGULO EQUILATERO"
    TRIANGULO_OBTUSANGULO = "TRIANGULO OBTUSANGULO"
